# Generated by Django 5.0.6 on 2024-05-22 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adminstrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cource_title', models.CharField(max_length=150)),
                ('descrition', models.CharField(max_length=150)),
                ('instructo_name', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('homework', models.CharField(max_length=150)),
                ('selected_cource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.adminstrator')),
            ],
        ),
    ]
