# Generated by Django 5.0.6 on 2024-05-22 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminstrator',
            name='descrition',
            field=models.TextField(max_length=150),
        ),
    ]
